# Generated by Django 5.2.17 on 2026-08-30 14:56

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('byte_size', models.BigIntegerField()),
                ('media_type', models.TextField()),
                ('original_filename', models.TextField()),
                ('storage_backend', models.CharField(choices=[('local', 'Local'), ('r2', 'Cloudflare R2')], max_length=10)),
                ('object_key', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_artifacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'artifact',
            },
        ),
        migrations.CreateModel(
            name='BenchmarkRevision',
            fields=[
                ('state', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('published', 'Published'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('version', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('revision_description', models.TextField()),
                ('recognition_status', models.CharField(choices=[('community_submitted', 'Community submitted'), ('admin_approved', 'Admin approved'), ('official', 'Official'), ('deprecated', 'Deprecated')], max_length=30)),
                ('manifest_artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='benchmark_manifests', to='registry.artifact')),
                ('previous_revision', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_revision', to='registry.benchmarkrevision')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_benchmark_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'benchmark_revision',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CircuitRevision',
            fields=[
                ('state', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('published', 'Published'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('revision_description', models.TextField()),
                ('is_css', models.BooleanField()),
                ('code_distance_upper_bound', models.PositiveIntegerField(blank=True, null=True)),
                ('circuit_distance_upper_bound', models.PositiveIntegerField(blank=True, null=True)),
                ('rounds', models.PositiveIntegerField(blank=True, null=True)),
                ('num_detectors', models.BigIntegerField()),
                ('num_errors', models.BigIntegerField()),
                ('num_observables', models.BigIntegerField()),
                ('dem_x_detectors_only', models.BooleanField()),
                ('dem_z_detectors_only', models.BooleanField()),
                ('stim_version', models.TextField()),
                ('dem_generation_method', models.TextField(default='stim.Circuit.detector_error_model')),
                ('dem_decompose_errors', models.BooleanField()),
                ('dem_flatten_loops', models.BooleanField()),
                ('dem_allow_gauge_detectors', models.BooleanField()),
                ('dem_approximate_disjoint_errors', models.JSONField()),
                ('dem_ignore_decomposition_failures', models.BooleanField()),
                ('dem_block_decomposition_from_introducing_remnant_edges', models.BooleanField()),
                ('detector_error_model_artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detector_error_models', to='registry.artifact')),
                ('manifest_artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='circuit_manifests', to='registry.artifact')),
                ('previous_revision', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_revision', to='registry.circuitrevision')),
                ('sampling_circuit_artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sampling_circuits', to='registry.artifact')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_circuit_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'circuit_revision',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BenchmarkRevisionItem',
            fields=[
                ('pk', models.CompositePrimaryKey('benchmark_revision_id', 'circuit_revision_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('is_required', models.BooleanField(default=True)),
                ('benchmark_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='registry.benchmarkrevision')),
                ('circuit_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='benchmark_items', to='registry.circuitrevision')),
            ],
            options={
                'db_table': 'benchmark_revision_item',
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('display_name', models.CharField(blank=True, max_length=200, null=True)),
                ('hidden_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credits', to=settings.AUTH_USER_MODEL)),
                ('benchmark_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='registry.benchmarkrevision')),
                ('circuit_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='registry.circuitrevision')),
            ],
            options={
                'db_table': 'credit',
            },
        ),
        migrations.CreateModel(
            name='CreditClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('retain_name_credit', models.BooleanField()),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, null=True)),
                ('claimant_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_claims', to=settings.AUTH_USER_MODEL)),
                ('created_account_credit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_by_claims', to='registry.credit')),
                ('name_credit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='registry.credit')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_credit_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'credit_claim',
            },
        ),
        migrations.CreateModel(
            name='DecoderVersion',
            fields=[
                ('state', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('published', 'Published'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('revision_description', models.TextField()),
                ('circuit_skeleton_preparation', models.CharField(choices=[('required', 'Required'), ('not_required', 'Not required')], max_length=20)),
                ('circuit_priors_preparation', models.CharField(choices=[('required', 'Required'), ('not_required', 'Not required')], max_length=20)),
                ('provides_failure_probability', models.BooleanField()),
                ('hyperparameter_definitions', models.TextField(blank=True, null=True)),
                ('hyperparameter_schema_artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decoder_hyperparameter_schemas', to='registry.artifact')),
                ('previous_version', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_version', to='registry.decoderversion')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_decoder_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'decoder_version',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='credit',
            name='decoder_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='registry.decoderversion'),
        ),
        migrations.CreateModel(
            name='BenchmarkAttempt',
            fields=[
                ('state', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('published', 'Published'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_benchmark_attempts', to=settings.AUTH_USER_MODEL)),
                ('benchmark_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='registry.benchmarkrevision')),
                ('decoder_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='benchmark_attempts', to='registry.decoderversion')),
            ],
            options={
                'db_table': 'benchmark_attempt',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EvaluatorRelease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.TextField(unique=True)),
                ('source_url', models.URLField(max_length=1000)),
                ('source_revision', models.TextField()),
                ('input_contract_url', models.URLField(max_length=1000)),
                ('summary_contract_url', models.URLField(max_length=1000)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('source_bundle_artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluator_source_bundles', to='registry.artifact')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_evaluator_releases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'evaluator_release',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('state', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('published', 'Published'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('machine_class', models.CharField(choices=[('cpu', 'CPU'), ('gpu', 'GPU'), ('fpga', 'FPGA'), ('asic', 'ASIC'), ('hybrid', 'Hybrid')], db_column='class', max_length=10)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('physical', 'Physical'), ('simulated', 'Simulated'), ('estimated', 'Estimated')], max_length=20)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_machines', to=settings.AUTH_USER_MODEL)),
                ('supersedes_machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='registry.machine')),
            ],
            options={
                'db_table': 'machine',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NoiseModel',
            fields=[
                ('state', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('published', 'Published'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('short_description', models.TextField()),
                ('paper_url', models.URLField(max_length=1000)),
                ('randomises_priors', models.BooleanField()),
                ('curation_status', models.CharField(choices=[('community', 'Community'), ('official', 'Official'), ('deprecated', 'Deprecated')], max_length=20)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_noise_models', to=settings.AUTH_USER_MODEL)),
                ('supersedes_noise_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='registry.noisemodel')),
            ],
            options={
                'db_table': 'noise_model',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='credit',
            name='noise_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='registry.noisemodel'),
        ),
        migrations.AddField(
            model_name='circuitrevision',
            name='noise_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='circuit_revisions', to='registry.noisemodel'),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('state', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('published', 'Published'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('hyperparameter_values', models.TextField(blank=True, null=True)),
                ('shots_total', models.BigIntegerField()),
                ('successful_shots', models.BigIntegerField()),
                ('logical_failure_shots', models.BigIntegerField()),
                ('timeout_shots', models.BigIntegerField()),
                ('decoder_error_shots', models.BigIntegerField()),
                ('failure_probability_shots', models.BigIntegerField()),
                ('latency_shots', models.BigIntegerField()),
                ('preparation_duration_seconds', models.DecimalField(blank=True, decimal_places=9, max_digits=24, null=True)),
                ('training_workload_description', models.TextField(blank=True, null=True)),
                ('software_environment', models.TextField(blank=True, null=True)),
                ('t_1000_ns', models.BigIntegerField(blank=True, null=True)),
                ('reproduction_status', models.CharField(choices=[('independent_reproduction', 'Independent reproduction'), ('decoder_author_verified', 'Decoder author verified')], max_length=30)),
                ('circuit_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='registry.circuitrevision')),
                ('decoder_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='registry.decoderversion')),
                ('evaluator_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='registry.evaluatorrelease')),
                ('hyperparameter_values_artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='result_hyperparameter_values', to='registry.artifact')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='results', to='registry.machine')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_results', to=settings.AUTH_USER_MODEL)),
                ('supersedes_result', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='registry.result')),
            ],
            options={
                'db_table': 'result',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('paper', 'Paper'), ('source', 'Source'), ('documentation', 'Documentation'), ('artifact', 'Artifact'), ('configuration', 'Configuration'), ('raw_trace', 'Raw trace'), ('other', 'Other')], max_length=20)),
                ('url', models.URLField(max_length=1000)),
                ('label', models.CharField(blank=True, max_length=200, null=True)),
                ('position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('benchmark_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_links', to='registry.benchmarkrevision')),
                ('circuit_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_links', to='registry.circuitrevision')),
                ('decoder_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_links', to='registry.decoderversion')),
                ('evaluator_release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_links', to='registry.evaluatorrelease')),
                ('noise_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_links', to='registry.noisemodel')),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_links', to='registry.result')),
            ],
            options={
                'db_table': 'external_link',
            },
        ),
        migrations.AddField(
            model_name='credit',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='registry.result'),
        ),
        migrations.CreateModel(
            name='BenchmarkAttemptResult',
            fields=[
                ('pk', models.CompositePrimaryKey('benchmark_attempt_id', 'circuit_revision_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('benchmark_attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_memberships', to='registry.benchmarkattempt')),
                ('circuit_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='benchmark_attempt_memberships', to='registry.circuitrevision')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='benchmark_attempt_memberships', to='registry.result')),
            ],
            options={
                'db_table': 'benchmark_attempt_result',
            },
        ),
        migrations.CreateModel(
            name='ArtifactAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.TextField()),
                ('position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='registry.artifact')),
                ('benchmark_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='artifact_attachments', to='registry.benchmarkrevision')),
                ('circuit_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='artifact_attachments', to='registry.circuitrevision')),
                ('decoder_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='artifact_attachments', to='registry.decoderversion')),
                ('evaluator_release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='artifact_attachments', to='registry.evaluatorrelease')),
                ('noise_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='artifact_attachments', to='registry.noisemodel')),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='artifact_attachments', to='registry.result')),
            ],
            options={
                'db_table': 'artifact_attachment',
            },
        ),
        migrations.CreateModel(
            name='ResultAuthorApprovalEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('approve', 'Approve'), ('revoke', 'Revoke')], max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_author_approval_events', to=settings.AUTH_USER_MODEL)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author_approval_events', to='registry.result')),
            ],
            options={
                'db_table': 'result_author_approval_event',
            },
        ),
        migrations.CreateModel(
            name='SchemaRelease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(choices=[('decoder', 'Decoder'), ('tag', 'Tag'), ('noise_model', 'Noise model'), ('circuit', 'Circuit'), ('machine', 'Machine'), ('evaluator', 'Evaluator'), ('result', 'Result'), ('benchmark', 'Benchmark')], max_length=20)),
                ('version', models.TextField()),
                ('permanent_url', models.URLField(max_length=500, unique=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('frozen', 'Frozen'), ('retired', 'Retired')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('definitions_artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='definition_releases', to='registry.artifact')),
                ('json_schema_artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='json_schema_releases', to='registry.artifact')),
            ],
            options={
                'db_table': 'schema_release',
            },
        ),
        migrations.AddField(
            model_name='result',
            name='schema_release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='registry.schemarelease'),
        ),
        migrations.AddField(
            model_name='noisemodel',
            name='schema_release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='noise_models', to='registry.schemarelease'),
        ),
        migrations.AddField(
            model_name='machine',
            name='schema_release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='registry.schemarelease'),
        ),
        migrations.AddField(
            model_name='evaluatorrelease',
            name='schema_release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluator_releases', to='registry.schemarelease'),
        ),
        migrations.AddField(
            model_name='decoderversion',
            name='schema_release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decoder_versions', to='registry.schemarelease'),
        ),
        migrations.AddField(
            model_name='circuitrevision',
            name='schema_release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='circuit_revisions', to='registry.schemarelease'),
        ),
        migrations.AddField(
            model_name='benchmarkrevision',
            name='schema_release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='benchmark_revisions', to='registry.schemarelease'),
        ),
        migrations.CreateModel(
            name='ScoreDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=200)),
                ('version', models.TextField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('definition_url', models.URLField(max_length=1000)),
                ('direction', models.CharField(choices=[('lower_is_better', 'Lower is better'), ('higher_is_better', 'Higher is better'), ('not_ranked', 'Not ranked')], max_length=20)),
                ('unit', models.TextField()),
                ('primary_value_kind', models.CharField(choices=[('estimate', 'Estimate'), ('lower_bound', 'Lower bound'), ('upper_bound', 'Upper bound')], max_length=20)),
                ('required_inputs', models.JSONField()),
                ('parameters', models.JSONField()),
                ('is_provisional', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField()),
                ('evaluator_release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='score_definitions', to='registry.evaluatorrelease')),
            ],
            options={
                'db_table': 'score_definition',
            },
        ),
        migrations.CreateModel(
            name='ResultScore',
            fields=[
                ('pk', models.CompositePrimaryKey('result_id', 'score_definition_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=20, max_digits=38)),
                ('point_estimate', models.DecimalField(blank=True, decimal_places=20, max_digits=38, null=True)),
                ('lower_bound', models.DecimalField(blank=True, decimal_places=20, max_digits=38, null=True)),
                ('upper_bound', models.DecimalField(blank=True, decimal_places=20, max_digits=38, null=True)),
                ('confidence_level', models.DecimalField(blank=True, decimal_places=7, max_digits=8, null=True)),
                ('sample_count', models.BigIntegerField(blank=True, null=True)),
                ('event_count', models.BigIntegerField(blank=True, null=True)),
                ('details', models.JSONField(default=dict)),
                ('evaluator_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_scores', to='registry.evaluatorrelease')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='registry.result')),
                ('score_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_scores', to='registry.scoredefinition')),
            ],
            options={
                'db_table': 'result_score',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('namespace', models.CharField(choices=[('algorithm', 'Algorithm'), ('experiment', 'Experiment'), ('code', 'Code')], max_length=20)),
                ('slug', models.SlugField(max_length=200)),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('custom', 'Custom'), ('official', 'Official'), ('deprecated', 'Deprecated')], default='custom', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curated_at', models.DateTimeField(blank=True, null=True)),
                ('canonical_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='registry.tag')),
                ('curated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='curated_tags', to=settings.AUTH_USER_MODEL)),
                ('schema_release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tags', to='registry.schemarelease')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='ModerationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('submitted', 'Submitted'), ('requested_changes', 'Requested changes'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published'), ('withdrawn', 'Withdrawn'), ('promoted_official', 'Promoted official'), ('deprecated', 'Deprecated'), ('merged', 'Merged'), ('admin_credit_claim_override', 'Admin credit claim override')], max_length=40)),
                ('note', models.TextField()),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moderation_events', to=settings.AUTH_USER_MODEL)),
                ('benchmark_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moderation_events', to='registry.benchmarkrevision')),
                ('circuit_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moderation_events', to='registry.circuitrevision')),
                ('decoder_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moderation_events', to='registry.decoderversion')),
                ('evaluator_release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moderation_events', to='registry.evaluatorrelease')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moderation_events', to='registry.machine')),
                ('noise_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moderation_events', to='registry.noisemodel')),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moderation_events', to='registry.result')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moderation_events', to='registry.tag')),
            ],
            options={
                'db_table': 'moderation_event',
            },
        ),
        migrations.CreateModel(
            name='DecoderVersionAlgorithmTag',
            fields=[
                ('pk', models.CompositePrimaryKey('decoder_version_id', 'tag_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('decoder_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='algorithm_tag_memberships', to='registry.decoderversion')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decoder_memberships', to='registry.tag')),
            ],
            options={
                'db_table': 'decoder_version_algorithm_tag',
            },
        ),
        migrations.AddField(
            model_name='decoderversion',
            name='algorithm_tags',
            field=models.ManyToManyField(related_name='decoder_versions', through='registry.DecoderVersionAlgorithmTag', to='registry.tag'),
        ),
        migrations.CreateModel(
            name='CircuitRevisionExperimentTag',
            fields=[
                ('pk', models.CompositePrimaryKey('circuit_revision_id', 'tag_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('circuit_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experiment_tag_memberships', to='registry.circuitrevision')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='circuit_experiment_memberships', to='registry.tag')),
            ],
            options={
                'db_table': 'circuit_revision_experiment_tag',
            },
        ),
        migrations.CreateModel(
            name='CircuitRevisionCodeTag',
            fields=[
                ('pk', models.CompositePrimaryKey('circuit_revision_id', 'tag_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('circuit_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='code_tag_memberships', to='registry.circuitrevision')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='circuit_code_memberships', to='registry.tag')),
            ],
            options={
                'db_table': 'circuit_revision_code_tag',
            },
        ),
        migrations.AddField(
            model_name='circuitrevision',
            name='code_tags',
            field=models.ManyToManyField(related_name='code_circuit_revisions', through='registry.CircuitRevisionCodeTag', to='registry.tag'),
        ),
        migrations.AddField(
            model_name='circuitrevision',
            name='experiment_tags',
            field=models.ManyToManyField(related_name='experiment_circuit_revisions', through='registry.CircuitRevisionExperimentTag', to='registry.tag'),
        ),
        migrations.AddConstraint(
            model_name='artifact',
            constraint=models.CheckConstraint(condition=models.Q(('sha256__regex', '^[0-9a-f]{64}$')), name='artifact_sha256_format'),
        ),
        migrations.AddConstraint(
            model_name='artifact',
            constraint=models.CheckConstraint(condition=models.Q(('byte_size__gte', 0)), name='artifact_byte_size_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='artifact',
            constraint=models.UniqueConstraint(fields=('storage_backend', 'object_key'), name='artifact_backend_object_key_uniq'),
        ),
        migrations.AddIndex(
            model_name='benchmarkrevisionitem',
            index=models.Index(fields=['benchmark_revision', 'position'], name='idx_benchmark_item_position'),
        ),
        migrations.AddConstraint(
            model_name='benchmarkrevisionitem',
            constraint=models.UniqueConstraint(fields=('benchmark_revision', 'position'), name='benchmark_item_revision_position_uniq'),
        ),
        migrations.AddConstraint(
            model_name='benchmarkrevisionitem',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1)), name='benchmark_item_position_positive'),
        ),
        migrations.AddConstraint(
            model_name='creditclaim',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'pending')), fields=('name_credit', 'claimant_account'), name='credit_claim_one_pending_uniq'),
        ),
        migrations.AddConstraint(
            model_name='creditclaim',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reviewed_at__isnull', True), ('reviewed_by__isnull', True), ('state__in', ['pending', 'cancelled'])), models.Q(('reviewed_at__isnull', False), ('reviewed_by__isnull', False), ('state__in', ['approved', 'rejected'])), _connector='OR'), name='credit_claim_review_state'),
        ),
        migrations.AddConstraint(
            model_name='creditclaim',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('created_account_credit__isnull', False), ('state', 'approved')), models.Q(models.Q(('state', 'approved'), _negated=True), ('created_account_credit__isnull', True)), _connector='OR'), name='credit_claim_created_credit_state'),
        ),
        migrations.AddConstraint(
            model_name='benchmarkattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('published_at__isnull', True), ('state__in', ['draft', 'pending_review']), ('withdrawn_at__isnull', True)), models.Q(('published_at__isnull', False), ('state', 'published'), ('withdrawn_at__isnull', True)), models.Q(('published_at__isnull', False), ('state', 'withdrawn'), ('withdrawn_at__isnull', False)), _connector='OR'), name='registry_benchmarkattempt_lifecycle_timestamps'),
        ),
        migrations.AddConstraint(
            model_name='externallink',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('pk__isnull', True), models.Q(('pk__isnull', True), _negated=True)), models.Q(('decoder_version__isnull', False), ('noise_model__isnull', True), ('circuit_revision__isnull', True), ('result__isnull', True), ('evaluator_release__isnull', True), ('benchmark_revision__isnull', True)), models.Q(('noise_model__isnull', False), ('decoder_version__isnull', True), ('circuit_revision__isnull', True), ('result__isnull', True), ('evaluator_release__isnull', True), ('benchmark_revision__isnull', True)), models.Q(('circuit_revision__isnull', False), ('decoder_version__isnull', True), ('noise_model__isnull', True), ('result__isnull', True), ('evaluator_release__isnull', True), ('benchmark_revision__isnull', True)), models.Q(('result__isnull', False), ('decoder_version__isnull', True), ('noise_model__isnull', True), ('circuit_revision__isnull', True), ('evaluator_release__isnull', True), ('benchmark_revision__isnull', True)), models.Q(('evaluator_release__isnull', False), ('decoder_version__isnull', True), ('noise_model__isnull', True), ('circuit_revision__isnull', True), ('result__isnull', True), ('benchmark_revision__isnull', True)), models.Q(('benchmark_revision__isnull', False), ('decoder_version__isnull', True), ('noise_model__isnull', True), ('circuit_revision__isnull', True), ('result__isnull', True), ('evaluator_release__isnull', True)), _connector='OR'), name='external_link_one_subject'),
        ),
        migrations.AddConstraint(
            model_name='externallink',
            constraint=models.UniqueConstraint(condition=models.Q(('decoder_version__isnull', False)), fields=('decoder_version', 'url'), name='external_link_decoder_version_url_uniq'),
        ),
        migrations.AddConstraint(
            model_name='externallink',
            constraint=models.UniqueConstraint(condition=models.Q(('noise_model__isnull', False)), fields=('noise_model', 'url'), name='external_link_noise_model_url_uniq'),
        ),
        migrations.AddConstraint(
            model_name='externallink',
            constraint=models.UniqueConstraint(condition=models.Q(('circuit_revision__isnull', False)), fields=('circuit_revision', 'url'), name='external_link_circuit_revision_url_uniq'),
        ),
        migrations.AddConstraint(
            model_name='externallink',
            constraint=models.UniqueConstraint(condition=models.Q(('result__isnull', False)), fields=('result', 'url'), name='external_link_result_url_uniq'),
        ),
        migrations.AddConstraint(
            model_name='externallink',
            constraint=models.UniqueConstraint(condition=models.Q(('evaluator_release__isnull', False)), fields=('evaluator_release', 'url'), name='external_link_evaluator_release_url_uniq'),
        ),
        migrations.AddConstraint(
            model_name='externallink',
            constraint=models.UniqueConstraint(condition=models.Q(('benchmark_revision__isnull', False)), fields=('benchmark_revision', 'url'), name='external_link_benchmark_revision_url_uniq'),
        ),
        migrations.AddIndex(
            model_name='credit',
            index=models.Index(condition=models.Q(('account__isnull', False), ('hidden_at__isnull', True)), fields=['account'], name='idx_credit_account'),
        ),
        migrations.AddConstraint(
            model_name='credit',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('pk__isnull', True), models.Q(('pk__isnull', True), _negated=True)), models.Q(('decoder_version__isnull', False), ('noise_model__isnull', True), ('circuit_revision__isnull', True), ('result__isnull', True), ('benchmark_revision__isnull', True)), models.Q(('noise_model__isnull', False), ('decoder_version__isnull', True), ('circuit_revision__isnull', True), ('result__isnull', True), ('benchmark_revision__isnull', True)), models.Q(('circuit_revision__isnull', False), ('decoder_version__isnull', True), ('noise_model__isnull', True), ('result__isnull', True), ('benchmark_revision__isnull', True)), models.Q(('result__isnull', False), ('decoder_version__isnull', True), ('noise_model__isnull', True), ('circuit_revision__isnull', True), ('benchmark_revision__isnull', True)), models.Q(('benchmark_revision__isnull', False), ('decoder_version__isnull', True), ('noise_model__isnull', True), ('circuit_revision__isnull', True), ('result__isnull', True)), _connector='OR'), name='credit_one_subject'),
        ),
        migrations.AddConstraint(
            model_name='credit',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('account__isnull', True), ('display_name__isnull', False)), models.Q(('account__isnull', False), ('display_name__isnull', True)), _connector='OR'), name='credit_one_identity_form'),
        ),
        migrations.AddConstraint(
            model_name='credit',
            constraint=models.CheckConstraint(condition=models.Q(('account__isnull', True), ('hidden_at__isnull', True), _connector='OR'), name='credit_account_not_hidden'),
        ),
        migrations.AddConstraint(
            model_name='credit',
            constraint=models.UniqueConstraint(condition=models.Q(('decoder_version__isnull', False), ('hidden_at__isnull', True)), fields=('decoder_version', 'position'), name='credit_decoder_version_visible_position_uniq'),
        ),
        migrations.AddConstraint(
            model_name='credit',
            constraint=models.UniqueConstraint(condition=models.Q(('noise_model__isnull', False), ('hidden_at__isnull', True)), fields=('noise_model', 'position'), name='credit_noise_model_visible_position_uniq'),
        ),
        migrations.AddConstraint(
            model_name='credit',
            constraint=models.UniqueConstraint(condition=models.Q(('circuit_revision__isnull', False), ('hidden_at__isnull', True)), fields=('circuit_revision', 'position'), name='credit_circuit_revision_visible_position_uniq'),
        ),
        migrations.AddConstraint(
            model_name='credit',
            constraint=models.UniqueConstraint(condition=models.Q(('result__isnull', False), ('hidden_at__isnull', True)), fields=('result', 'position'), name='credit_result_visible_position_uniq'),
        ),
        migrations.AddConstraint(
            model_name='credit',
            constraint=models.UniqueConstraint(condition=models.Q(('benchmark_revision__isnull', False), ('hidden_at__isnull', True)), fields=('benchmark_revision', 'position'), name='credit_benchmark_revision_visible_position_uniq'),
        ),
        migrations.AddConstraint(
            model_name='benchmarkattemptresult',
            constraint=models.UniqueConstraint(fields=('benchmark_attempt', 'result'), name='benchmark_attempt_result_uniq'),
        ),
        migrations.AddConstraint(
            model_name='artifactattachment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('pk__isnull', True), models.Q(('pk__isnull', True), _negated=True)), models.Q(('decoder_version__isnull', False), ('noise_model__isnull', True), ('circuit_revision__isnull', True), ('result__isnull', True), ('evaluator_release__isnull', True), ('benchmark_revision__isnull', True)), models.Q(('noise_model__isnull', False), ('decoder_version__isnull', True), ('circuit_revision__isnull', True), ('result__isnull', True), ('evaluator_release__isnull', True), ('benchmark_revision__isnull', True)), models.Q(('circuit_revision__isnull', False), ('decoder_version__isnull', True), ('noise_model__isnull', True), ('result__isnull', True), ('evaluator_release__isnull', True), ('benchmark_revision__isnull', True)), models.Q(('result__isnull', False), ('decoder_version__isnull', True), ('noise_model__isnull', True), ('circuit_revision__isnull', True), ('evaluator_release__isnull', True), ('benchmark_revision__isnull', True)), models.Q(('evaluator_release__isnull', False), ('decoder_version__isnull', True), ('noise_model__isnull', True), ('circuit_revision__isnull', True), ('result__isnull', True), ('benchmark_revision__isnull', True)), models.Q(('benchmark_revision__isnull', False), ('decoder_version__isnull', True), ('noise_model__isnull', True), ('circuit_revision__isnull', True), ('result__isnull', True), ('evaluator_release__isnull', True)), _connector='OR'), name='artifact_attachment_one_subject'),
        ),
        migrations.AddConstraint(
            model_name='artifactattachment',
            constraint=models.UniqueConstraint(condition=models.Q(('decoder_version__isnull', False)), fields=('decoder_version', 'role', 'position'), name='attachment_decoder_version_role_position_uniq'),
        ),
        migrations.AddConstraint(
            model_name='artifactattachment',
            constraint=models.UniqueConstraint(condition=models.Q(('noise_model__isnull', False)), fields=('noise_model', 'role', 'position'), name='attachment_noise_model_role_position_uniq'),
        ),
        migrations.AddConstraint(
            model_name='artifactattachment',
            constraint=models.UniqueConstraint(condition=models.Q(('circuit_revision__isnull', False)), fields=('circuit_revision', 'role', 'position'), name='attachment_circuit_revision_role_position_uniq'),
        ),
        migrations.AddConstraint(
            model_name='artifactattachment',
            constraint=models.UniqueConstraint(condition=models.Q(('result__isnull', False)), fields=('result', 'role', 'position'), name='attachment_result_role_position_uniq'),
        ),
        migrations.AddConstraint(
            model_name='artifactattachment',
            constraint=models.UniqueConstraint(condition=models.Q(('evaluator_release__isnull', False)), fields=('evaluator_release', 'role', 'position'), name='attachment_evaluator_release_role_position_uniq'),
        ),
        migrations.AddConstraint(
            model_name='artifactattachment',
            constraint=models.UniqueConstraint(condition=models.Q(('benchmark_revision__isnull', False)), fields=('benchmark_revision', 'role', 'position'), name='attachment_benchmark_revision_role_position_uniq'),
        ),
        migrations.AddConstraint(
            model_name='artifactattachment',
            constraint=models.UniqueConstraint(condition=models.Q(('decoder_version__isnull', False)), fields=('decoder_version', 'artifact'), name='attachment_decoder_version_artifact_uniq'),
        ),
        migrations.AddConstraint(
            model_name='artifactattachment',
            constraint=models.UniqueConstraint(condition=models.Q(('noise_model__isnull', False)), fields=('noise_model', 'artifact'), name='attachment_noise_model_artifact_uniq'),
        ),
        migrations.AddConstraint(
            model_name='artifactattachment',
            constraint=models.UniqueConstraint(condition=models.Q(('circuit_revision__isnull', False)), fields=('circuit_revision', 'artifact'), name='attachment_circuit_revision_artifact_uniq'),
        ),
        migrations.AddConstraint(
            model_name='artifactattachment',
            constraint=models.UniqueConstraint(condition=models.Q(('result__isnull', False)), fields=('result', 'artifact'), name='attachment_result_artifact_uniq'),
        ),
        migrations.AddConstraint(
            model_name='artifactattachment',
            constraint=models.UniqueConstraint(condition=models.Q(('evaluator_release__isnull', False)), fields=('evaluator_release', 'artifact'), name='attachment_evaluator_release_artifact_uniq'),
        ),
        migrations.AddConstraint(
            model_name='artifactattachment',
            constraint=models.UniqueConstraint(condition=models.Q(('benchmark_revision__isnull', False)), fields=('benchmark_revision', 'artifact'), name='attachment_benchmark_revision_artifact_uniq'),
        ),
        migrations.AddConstraint(
            model_name='schemarelease',
            constraint=models.UniqueConstraint(fields=('record_type', 'version'), name='schema_release_record_type_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='schemarelease',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('frozen_at__isnull', True), ('state', 'draft')), models.Q(('frozen_at__isnull', False), ('state__in', ['frozen', 'retired'])), _connector='OR'), name='schema_release_frozen_timestamp'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['circuit_revision', 'state', '-created_at'], name='idx_result_circuit_state'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['decoder_version', 'state', '-created_at'], name='idx_result_decoder_state'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(condition=models.Q(('machine__isnull', False)), fields=['machine', 'state'], name='idx_result_machine'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(condition=models.Q(('supersedes_result__isnull', False)), fields=['supersedes_result'], name='idx_result_supersedes'),
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('published_at__isnull', True), ('state__in', ['draft', 'pending_review']), ('withdrawn_at__isnull', True)), models.Q(('published_at__isnull', False), ('state', 'published'), ('withdrawn_at__isnull', True)), models.Q(('published_at__isnull', False), ('state', 'withdrawn'), ('withdrawn_at__isnull', False)), _connector='OR'), name='registry_result_lifecycle_timestamps'),
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.CheckConstraint(condition=models.Q(('shots_total__gte', 1)), name='result_shots_total_positive'),
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.CheckConstraint(condition=models.Q(('successful_shots__gte', 0), ('logical_failure_shots__gte', 0), ('timeout_shots__gte', 0), ('decoder_error_shots__gte', 0), ('failure_probability_shots__gte', 0), ('latency_shots__gte', 0)), name='result_shot_counts_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.CheckConstraint(condition=models.Q(('shots_total', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('successful_shots'), '+', models.F('logical_failure_shots')), '+', models.F('timeout_shots')), '+', models.F('decoder_error_shots')))), name='result_outcome_counts_sum'),
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.CheckConstraint(condition=models.Q(('failure_probability_shots__lte', django.db.models.expressions.CombinedExpression(models.F('successful_shots'), '+', models.F('logical_failure_shots')))), name='result_probability_shots_valid'),
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.CheckConstraint(condition=models.Q(('latency_shots__lte', django.db.models.expressions.CombinedExpression(models.F('successful_shots'), '+', models.F('logical_failure_shots')))), name='result_latency_shots_valid'),
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.CheckConstraint(condition=models.Q(('preparation_duration_seconds__isnull', True), ('preparation_duration_seconds__gte', 0), _connector='OR'), name='result_preparation_duration_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.CheckConstraint(condition=models.Q(('t_1000_ns__isnull', True), ('t_1000_ns__gt', 0), _connector='OR'), name='result_t_1000_positive'),
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.CheckConstraint(condition=models.Q(('supersedes_result__isnull', True), models.Q(('supersedes_result', models.F('id')), _negated=True), _connector='OR'), name='result_supersedes_not_self'),
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.UniqueConstraint(fields=('id', 'evaluator_version'), name='result_id_evaluator_uniq'),
        ),
        migrations.AddConstraint(
            model_name='noisemodel',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('published_at__isnull', True), ('state__in', ['draft', 'pending_review']), ('withdrawn_at__isnull', True)), models.Q(('published_at__isnull', False), ('state', 'published'), ('withdrawn_at__isnull', True)), models.Q(('published_at__isnull', False), ('state', 'withdrawn'), ('withdrawn_at__isnull', False)), _connector='OR'), name='registry_noisemodel_lifecycle_timestamps'),
        ),
        migrations.AddConstraint(
            model_name='noisemodel',
            constraint=models.CheckConstraint(condition=models.Q(('supersedes_noise_model__isnull', True), models.Q(('supersedes_noise_model', models.F('id')), _negated=True), _connector='OR'), name='noise_model_supersedes_not_self'),
        ),
        migrations.AddConstraint(
            model_name='machine',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('published_at__isnull', True), ('state__in', ['draft', 'pending_review']), ('withdrawn_at__isnull', True)), models.Q(('published_at__isnull', False), ('state', 'published'), ('withdrawn_at__isnull', True)), models.Q(('published_at__isnull', False), ('state', 'withdrawn'), ('withdrawn_at__isnull', False)), _connector='OR'), name='registry_machine_lifecycle_timestamps'),
        ),
        migrations.AddConstraint(
            model_name='machine',
            constraint=models.CheckConstraint(condition=models.Q(('supersedes_machine__isnull', True), models.Q(('supersedes_machine', models.F('id')), _negated=True), _connector='OR'), name='machine_supersedes_not_self'),
        ),
        migrations.AddConstraint(
            model_name='evaluatorrelease',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('published_at__isnull', True), ('state', 'draft'), ('withdrawn_at__isnull', True)), models.Q(('published_at__isnull', False), ('state', 'published'), ('withdrawn_at__isnull', True)), models.Q(('published_at__isnull', False), ('state', 'withdrawn'), ('withdrawn_at__isnull', False)), _connector='OR'), name='evaluator_release_lifecycle_timestamps'),
        ),
        migrations.AddConstraint(
            model_name='benchmarkrevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('published_at__isnull', True), ('state__in', ['draft', 'pending_review']), ('withdrawn_at__isnull', True)), models.Q(('published_at__isnull', False), ('state', 'published'), ('withdrawn_at__isnull', True)), models.Q(('published_at__isnull', False), ('state', 'withdrawn'), ('withdrawn_at__isnull', False)), _connector='OR'), name='registry_benchmarkrevision_lifecycle_timestamps'),
        ),
        migrations.AddConstraint(
            model_name='benchmarkrevision',
            constraint=models.CheckConstraint(condition=models.Q(('previous_revision__isnull', True), models.Q(('previous_revision', models.F('id')), _negated=True), _connector='OR'), name='benchmark_revision_previous_not_self'),
        ),
        migrations.AddConstraint(
            model_name='scoredefinition',
            constraint=models.UniqueConstraint(fields=('evaluator_release', 'key'), name='score_definition_release_key_uniq'),
        ),
        migrations.AddConstraint(
            model_name='scoredefinition',
            constraint=models.UniqueConstraint(fields=('evaluator_release', 'display_order'), name='score_definition_release_order_uniq'),
        ),
        migrations.AddConstraint(
            model_name='scoredefinition',
            constraint=models.UniqueConstraint(fields=('id', 'evaluator_release'), name='score_definition_id_release_uniq'),
        ),
        migrations.AddConstraint(
            model_name='scoredefinition',
            constraint=models.CheckConstraint(condition=models.Q(('display_order__gte', 1)), name='score_definition_display_order_positive'),
        ),
        migrations.AddIndex(
            model_name='resultscore',
            index=models.Index(fields=['score_definition', 'value', 'result'], name='idx_result_score_ranking'),
        ),
        migrations.AddConstraint(
            model_name='resultscore',
            constraint=models.CheckConstraint(condition=models.Q(('confidence_level__isnull', True), models.Q(('confidence_level__gt', 0), ('confidence_level__lt', 1)), _connector='OR'), name='result_score_confidence_range'),
        ),
        migrations.AddConstraint(
            model_name='resultscore',
            constraint=models.CheckConstraint(condition=models.Q(('sample_count__isnull', True), ('sample_count__gte', 0), _connector='OR'), name='result_score_sample_count_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='resultscore',
            constraint=models.CheckConstraint(condition=models.Q(('event_count__isnull', True), ('event_count__gte', 0), _connector='OR'), name='result_score_event_count_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['namespace', 'status', 'label'], name='idx_tag_search'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('namespace', 'slug'), name='tag_namespace_slug_uniq'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.CheckConstraint(condition=models.Q(('slug__regex', '^[a-z0-9]+(?:-[a-z0-9]+)*$')), name='tag_slug_format'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.CheckConstraint(condition=models.Q(('canonical_tag__isnull', True), models.Q(('canonical_tag', models.F('id')), _negated=True), _connector='OR'), name='tag_canonical_not_self'),
        ),
        migrations.AddConstraint(
            model_name='moderationevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('pk__isnull', True), models.Q(('pk__isnull', True), _negated=True)), models.Q(('decoder_version__isnull', False), ('noise_model__isnull', True), ('circuit_revision__isnull', True), ('machine__isnull', True), ('result__isnull', True), ('tag__isnull', True), ('benchmark_revision__isnull', True), ('evaluator_release__isnull', True)), models.Q(('noise_model__isnull', False), ('decoder_version__isnull', True), ('circuit_revision__isnull', True), ('machine__isnull', True), ('result__isnull', True), ('tag__isnull', True), ('benchmark_revision__isnull', True), ('evaluator_release__isnull', True)), models.Q(('circuit_revision__isnull', False), ('decoder_version__isnull', True), ('noise_model__isnull', True), ('machine__isnull', True), ('result__isnull', True), ('tag__isnull', True), ('benchmark_revision__isnull', True), ('evaluator_release__isnull', True)), models.Q(('machine__isnull', False), ('decoder_version__isnull', True), ('noise_model__isnull', True), ('circuit_revision__isnull', True), ('result__isnull', True), ('tag__isnull', True), ('benchmark_revision__isnull', True), ('evaluator_release__isnull', True)), models.Q(('result__isnull', False), ('decoder_version__isnull', True), ('noise_model__isnull', True), ('circuit_revision__isnull', True), ('machine__isnull', True), ('tag__isnull', True), ('benchmark_revision__isnull', True), ('evaluator_release__isnull', True)), models.Q(('tag__isnull', False), ('decoder_version__isnull', True), ('noise_model__isnull', True), ('circuit_revision__isnull', True), ('machine__isnull', True), ('result__isnull', True), ('benchmark_revision__isnull', True), ('evaluator_release__isnull', True)), models.Q(('benchmark_revision__isnull', False), ('decoder_version__isnull', True), ('noise_model__isnull', True), ('circuit_revision__isnull', True), ('machine__isnull', True), ('result__isnull', True), ('tag__isnull', True), ('evaluator_release__isnull', True)), models.Q(('evaluator_release__isnull', False), ('decoder_version__isnull', True), ('noise_model__isnull', True), ('circuit_revision__isnull', True), ('machine__isnull', True), ('result__isnull', True), ('tag__isnull', True), ('benchmark_revision__isnull', True)), _connector='OR'), name='moderation_event_one_subject'),
        ),
        migrations.AddConstraint(
            model_name='decoderversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('published_at__isnull', True), ('state__in', ['draft', 'pending_review']), ('withdrawn_at__isnull', True)), models.Q(('published_at__isnull', False), ('state', 'published'), ('withdrawn_at__isnull', True)), models.Q(('published_at__isnull', False), ('state', 'withdrawn'), ('withdrawn_at__isnull', False)), _connector='OR'), name='registry_decoderversion_lifecycle_timestamps'),
        ),
        migrations.AddConstraint(
            model_name='decoderversion',
            constraint=models.CheckConstraint(condition=models.Q(('previous_version__isnull', True), models.Q(('previous_version', models.F('id')), _negated=True), _connector='OR'), name='decoder_version_previous_not_self'),
        ),
        migrations.AddConstraint(
            model_name='circuitrevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('published_at__isnull', True), ('state__in', ['draft', 'pending_review']), ('withdrawn_at__isnull', True)), models.Q(('published_at__isnull', False), ('state', 'published'), ('withdrawn_at__isnull', True)), models.Q(('published_at__isnull', False), ('state', 'withdrawn'), ('withdrawn_at__isnull', False)), _connector='OR'), name='registry_circuitrevision_lifecycle_timestamps'),
        ),
        migrations.AddConstraint(
            model_name='circuitrevision',
            constraint=models.CheckConstraint(condition=models.Q(('previous_revision__isnull', True), models.Q(('previous_revision', models.F('id')), _negated=True), _connector='OR'), name='circuit_revision_previous_not_self'),
        ),
        migrations.AddConstraint(
            model_name='circuitrevision',
            constraint=models.CheckConstraint(condition=models.Q(('code_distance_upper_bound__isnull', True), ('code_distance_upper_bound__gte', 1), _connector='OR'), name='circuit_code_distance_positive'),
        ),
        migrations.AddConstraint(
            model_name='circuitrevision',
            constraint=models.CheckConstraint(condition=models.Q(('circuit_distance_upper_bound__isnull', True), ('circuit_distance_upper_bound__gte', 1), _connector='OR'), name='circuit_fault_distance_positive'),
        ),
        migrations.AddConstraint(
            model_name='circuitrevision',
            constraint=models.CheckConstraint(condition=models.Q(('rounds__isnull', True), ('rounds__gte', 1), _connector='OR'), name='circuit_rounds_positive'),
        ),
        migrations.AddConstraint(
            model_name='circuitrevision',
            constraint=models.CheckConstraint(condition=models.Q(('num_detectors__gte', 0)), name='circuit_num_detectors_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='circuitrevision',
            constraint=models.CheckConstraint(condition=models.Q(('num_errors__gte', 0)), name='circuit_num_errors_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='circuitrevision',
            constraint=models.CheckConstraint(condition=models.Q(('num_observables__gte', 1)), name='circuit_num_observables_positive'),
        ),
        migrations.AddConstraint(
            model_name='circuitrevision',
            constraint=models.CheckConstraint(condition=models.Q(('is_css', True), models.Q(('dem_x_detectors_only', False), ('dem_z_detectors_only', False)), _connector='OR'), name='circuit_detector_only_implies_css'),
        ),
        migrations.AddConstraint(
            model_name='circuitrevision',
            constraint=models.CheckConstraint(condition=models.Q(('num_detectors', 0), ('dem_x_detectors_only', False), ('dem_z_detectors_only', False), _connector='OR'), name='circuit_detector_basis_not_both'),
        ),
        migrations.AddConstraint(
            model_name='circuitrevision',
            constraint=models.CheckConstraint(condition=models.Q(('dem_generation_method', 'stim.Circuit.detector_error_model')), name='circuit_dem_generation_method_fixed'),
        ),
    ]
