# Generated by Django 5.2.17 on 2026-08-30 14:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='artifact',
            constraint=models.CheckConstraint(condition=models.Q(('storage_backend__in', ['local', 'r2'])), name='artifact_storage_backend_valid'),
        ),
        migrations.AddConstraint(
            model_name='artifactattachment',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['source_archive', 'documentation', 'configuration', 'reproduction_bundle', 'other'])), name='artifact_attachment_role_valid'),
        ),
        migrations.AddConstraint(
            model_name='artifactattachment',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1)), name='artifact_attachment_position_positive'),
        ),
        migrations.AddConstraint(
            model_name='benchmarkrevision',
            constraint=models.CheckConstraint(condition=models.Q(('recognition_status__in', ['community_submitted', 'admin_approved', 'official', 'deprecated'])), name='benchmark_recognition_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='credit',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1)), name='credit_position_positive'),
        ),
        migrations.AddConstraint(
            model_name='decoderversion',
            constraint=models.CheckConstraint(condition=models.Q(('circuit_skeleton_preparation__in', ['required', 'not_required'])), name='decoder_skeleton_preparation_valid'),
        ),
        migrations.AddConstraint(
            model_name='decoderversion',
            constraint=models.CheckConstraint(condition=models.Q(('circuit_priors_preparation__in', ['required', 'not_required'])), name='decoder_priors_preparation_valid'),
        ),
        migrations.AddConstraint(
            model_name='externallink',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['paper', 'source', 'documentation', 'artifact', 'configuration', 'raw_trace', 'other'])), name='external_link_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='externallink',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1)), name='external_link_position_positive'),
        ),
        migrations.AddConstraint(
            model_name='machine',
            constraint=models.CheckConstraint(condition=models.Q(('machine_class__in', ['cpu', 'gpu', 'fpga', 'asic', 'hybrid'])), name='machine_class_valid'),
        ),
        migrations.AddConstraint(
            model_name='machine',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['physical', 'simulated', 'estimated'])), name='machine_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='moderationevent',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ['submitted', 'requested_changes', 'approved', 'rejected', 'published', 'withdrawn', 'promoted_official', 'deprecated', 'merged', 'admin_credit_claim_override'])), name='moderation_event_action_valid'),
        ),
        migrations.AddConstraint(
            model_name='noisemodel',
            constraint=models.CheckConstraint(condition=models.Q(('curation_status__in', ['community', 'official', 'deprecated'])), name='noise_model_curation_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.CheckConstraint(condition=models.Q(('reproduction_status__in', ['independent_reproduction', 'decoder_author_verified'])), name='result_reproduction_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='resultauthorapprovalevent',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ['approve', 'revoke'])), name='result_author_approval_action_valid'),
        ),
        migrations.AddConstraint(
            model_name='schemarelease',
            constraint=models.CheckConstraint(condition=models.Q(('record_type__in', ['decoder', 'tag', 'noise_model', 'circuit', 'machine', 'evaluator', 'result', 'benchmark'])), name='schema_release_record_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='scoredefinition',
            constraint=models.CheckConstraint(condition=models.Q(('direction__in', ['lower_is_better', 'higher_is_better', 'not_ranked'])), name='score_definition_direction_valid'),
        ),
        migrations.AddConstraint(
            model_name='scoredefinition',
            constraint=models.CheckConstraint(condition=models.Q(('primary_value_kind__in', ['estimate', 'lower_bound', 'upper_bound'])), name='score_definition_primary_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.CheckConstraint(condition=models.Q(('namespace__in', ['algorithm', 'experiment', 'code'])), name='tag_namespace_valid'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['custom', 'official', 'deprecated'])), name='tag_status_valid'),
        ),
    ]
