# Generated by Django 5.2.17 on 2026-08-31 18:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0004_tag_display_color"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="benchmarkattempt",
            name="registry_benchmarkattempt_lifecycle_timestamps",
        ),
        migrations.RemoveConstraint(
            model_name="benchmarkrevision",
            name="registry_benchmarkrevision_lifecycle_timestamps",
        ),
        migrations.RemoveConstraint(
            model_name="circuitrevision",
            name="registry_circuitrevision_lifecycle_timestamps",
        ),
        migrations.RemoveConstraint(
            model_name="decoderversion",
            name="registry_decoderversion_lifecycle_timestamps",
        ),
        migrations.RemoveConstraint(
            model_name="machine",
            name="registry_machine_lifecycle_timestamps",
        ),
        migrations.RemoveConstraint(
            model_name="moderationevent",
            name="moderation_event_action_valid",
        ),
        migrations.RemoveConstraint(
            model_name="noisemodel",
            name="registry_noisemodel_lifecycle_timestamps",
        ),
        migrations.RemoveConstraint(
            model_name="result",
            name="registry_result_lifecycle_timestamps",
        ),
        migrations.AlterField(
            model_name="benchmarkattempt",
            name="state",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_review", "Pending review"),
                    ("pending_reapproval", "Pending reapproval"),
                    ("published", "Published"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="benchmarkrevision",
            name="state",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_review", "Pending review"),
                    ("pending_reapproval", "Pending reapproval"),
                    ("published", "Published"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="circuitrevision",
            name="state",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_review", "Pending review"),
                    ("pending_reapproval", "Pending reapproval"),
                    ("published", "Published"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="decoderversion",
            name="state",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_review", "Pending review"),
                    ("pending_reapproval", "Pending reapproval"),
                    ("published", "Published"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="state",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_review", "Pending review"),
                    ("pending_reapproval", "Pending reapproval"),
                    ("published", "Published"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="moderationevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted"),
                    ("edited", "Edited"),
                    ("resubmitted", "Resubmitted"),
                    ("requested_changes", "Requested changes"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("published", "Published"),
                    ("withdrawn", "Withdrawn"),
                    ("promoted_official", "Promoted official"),
                    ("deprecated", "Deprecated"),
                    ("merged", "Merged"),
                    ("admin_credit_claim_override", "Admin credit claim override"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="noisemodel",
            name="state",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_review", "Pending review"),
                    ("pending_reapproval", "Pending reapproval"),
                    ("published", "Published"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="result",
            name="state",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_review", "Pending review"),
                    ("pending_reapproval", "Pending reapproval"),
                    ("published", "Published"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="benchmarkattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("published_at__isnull", True),
                        (
                            "state__in",
                            ["draft", "pending_review", "pending_reapproval"],
                        ),
                        ("withdrawn_at__isnull", True),
                    ),
                    models.Q(
                        ("published_at__isnull", False),
                        ("state", "published"),
                        ("withdrawn_at__isnull", True),
                    ),
                    models.Q(
                        ("published_at__isnull", False),
                        ("state", "withdrawn"),
                        ("withdrawn_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="registry_benchmarkattempt_lifecycle_timestamps",
            ),
        ),
        migrations.AddConstraint(
            model_name="benchmarkrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("published_at__isnull", True),
                        (
                            "state__in",
                            ["draft", "pending_review", "pending_reapproval"],
                        ),
                        ("withdrawn_at__isnull", True),
                    ),
                    models.Q(
                        ("published_at__isnull", False),
                        ("state", "published"),
                        ("withdrawn_at__isnull", True),
                    ),
                    models.Q(
                        ("published_at__isnull", False),
                        ("state", "withdrawn"),
                        ("withdrawn_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="registry_benchmarkrevision_lifecycle_timestamps",
            ),
        ),
        migrations.AddConstraint(
            model_name="circuitrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("published_at__isnull", True),
                        (
                            "state__in",
                            ["draft", "pending_review", "pending_reapproval"],
                        ),
                        ("withdrawn_at__isnull", True),
                    ),
                    models.Q(
                        ("published_at__isnull", False),
                        ("state", "published"),
                        ("withdrawn_at__isnull", True),
                    ),
                    models.Q(
                        ("published_at__isnull", False),
                        ("state", "withdrawn"),
                        ("withdrawn_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="registry_circuitrevision_lifecycle_timestamps",
            ),
        ),
        migrations.AddConstraint(
            model_name="decoderversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("published_at__isnull", True),
                        (
                            "state__in",
                            ["draft", "pending_review", "pending_reapproval"],
                        ),
                        ("withdrawn_at__isnull", True),
                    ),
                    models.Q(
                        ("published_at__isnull", False),
                        ("state", "published"),
                        ("withdrawn_at__isnull", True),
                    ),
                    models.Q(
                        ("published_at__isnull", False),
                        ("state", "withdrawn"),
                        ("withdrawn_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="registry_decoderversion_lifecycle_timestamps",
            ),
        ),
        migrations.AddConstraint(
            model_name="machine",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("published_at__isnull", True),
                        (
                            "state__in",
                            ["draft", "pending_review", "pending_reapproval"],
                        ),
                        ("withdrawn_at__isnull", True),
                    ),
                    models.Q(
                        ("published_at__isnull", False),
                        ("state", "published"),
                        ("withdrawn_at__isnull", True),
                    ),
                    models.Q(
                        ("published_at__isnull", False),
                        ("state", "withdrawn"),
                        ("withdrawn_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="registry_machine_lifecycle_timestamps",
            ),
        ),
        migrations.AddConstraint(
            model_name="moderationevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "action__in",
                        [
                            "submitted",
                            "edited",
                            "resubmitted",
                            "requested_changes",
                            "approved",
                            "rejected",
                            "published",
                            "withdrawn",
                            "promoted_official",
                            "deprecated",
                            "merged",
                            "admin_credit_claim_override",
                        ],
                    )
                ),
                name="moderation_event_action_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="noisemodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("published_at__isnull", True),
                        (
                            "state__in",
                            ["draft", "pending_review", "pending_reapproval"],
                        ),
                        ("withdrawn_at__isnull", True),
                    ),
                    models.Q(
                        ("published_at__isnull", False),
                        ("state", "published"),
                        ("withdrawn_at__isnull", True),
                    ),
                    models.Q(
                        ("published_at__isnull", False),
                        ("state", "withdrawn"),
                        ("withdrawn_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="registry_noisemodel_lifecycle_timestamps",
            ),
        ),
        migrations.AddConstraint(
            model_name="result",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("published_at__isnull", True),
                        (
                            "state__in",
                            ["draft", "pending_review", "pending_reapproval"],
                        ),
                        ("withdrawn_at__isnull", True),
                    ),
                    models.Q(
                        ("published_at__isnull", False),
                        ("state", "published"),
                        ("withdrawn_at__isnull", True),
                    ),
                    models.Q(
                        ("published_at__isnull", False),
                        ("state", "withdrawn"),
                        ("withdrawn_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="registry_result_lifecycle_timestamps",
            ),
        ),
    ]
