# Generated by Django 5.2.17 on 2026-09-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0008_circuit_dem_approximate_disjoint_errors_boolean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externallink',
            name='kind',
            field=models.CharField(choices=[('paper', 'Paper'), ('source', 'Source'), ('documentation', 'Documentation'), ('artifact', 'File'), ('configuration', 'Configuration'), ('raw_trace', 'Raw trace'), ('other', 'Other')], max_length=20),
        ),
    ]
