# Generated by Django 5.2.17 on 2026-09-01 10:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0009_alter_externallink_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='benchmarkattempt',
            name='registry_benchmarkattempt_lifecycle_timestamps',
        ),
        migrations.RemoveConstraint(
            model_name='benchmarkrevision',
            name='registry_benchmarkrevision_lifecycle_timestamps',
        ),
        migrations.RemoveConstraint(
            model_name='circuitrevision',
            name='registry_circuitrevision_lifecycle_timestamps',
        ),
        migrations.RemoveConstraint(
            model_name='decoderversion',
            name='registry_decoderversion_lifecycle_timestamps',
        ),
        migrations.RemoveConstraint(
            model_name='machine',
            name='registry_machine_lifecycle_timestamps',
        ),
        migrations.RemoveConstraint(
            model_name='noisemodel',
            name='registry_noisemodel_lifecycle_timestamps',
        ),
        migrations.RemoveConstraint(
            model_name='result',
            name='registry_result_lifecycle_timestamps',
        ),
        migrations.AlterField(
            model_name='benchmarkattempt',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('pending_reapproval', 'Pending reapproval'), ('changes_requested', 'Changes requested'), ('rejected', 'Rejected'), ('published', 'Published'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='benchmarkrevision',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('pending_reapproval', 'Pending reapproval'), ('changes_requested', 'Changes requested'), ('rejected', 'Rejected'), ('published', 'Published'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='circuitrevision',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('pending_reapproval', 'Pending reapproval'), ('changes_requested', 'Changes requested'), ('rejected', 'Rejected'), ('published', 'Published'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='decoderversion',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('pending_reapproval', 'Pending reapproval'), ('changes_requested', 'Changes requested'), ('rejected', 'Rejected'), ('published', 'Published'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='machine',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('pending_reapproval', 'Pending reapproval'), ('changes_requested', 'Changes requested'), ('rejected', 'Rejected'), ('published', 'Published'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='noisemodel',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('pending_reapproval', 'Pending reapproval'), ('changes_requested', 'Changes requested'), ('rejected', 'Rejected'), ('published', 'Published'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='result',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('pending_reapproval', 'Pending reapproval'), ('changes_requested', 'Changes requested'), ('rejected', 'Rejected'), ('published', 'Published'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='benchmarkattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('published_at__isnull', True), ('state__in', ['draft', 'pending_review', 'pending_reapproval', 'changes_requested', 'rejected']), ('withdrawn_at__isnull', True)), models.Q(('published_at__isnull', False), ('state', 'published'), ('withdrawn_at__isnull', True)), models.Q(('published_at__isnull', False), ('state', 'withdrawn'), ('withdrawn_at__isnull', False)), _connector='OR'), name='registry_benchmarkattempt_lifecycle_timestamps'),
        ),
        migrations.AddConstraint(
            model_name='benchmarkrevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('published_at__isnull', True), ('state__in', ['draft', 'pending_review', 'pending_reapproval', 'changes_requested', 'rejected']), ('withdrawn_at__isnull', True)), models.Q(('published_at__isnull', False), ('state', 'published'), ('withdrawn_at__isnull', True)), models.Q(('published_at__isnull', False), ('state', 'withdrawn'), ('withdrawn_at__isnull', False)), _connector='OR'), name='registry_benchmarkrevision_lifecycle_timestamps'),
        ),
        migrations.AddConstraint(
            model_name='circuitrevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('published_at__isnull', True), ('state__in', ['draft', 'pending_review', 'pending_reapproval', 'changes_requested', 'rejected']), ('withdrawn_at__isnull', True)), models.Q(('published_at__isnull', False), ('state', 'published'), ('withdrawn_at__isnull', True)), models.Q(('published_at__isnull', False), ('state', 'withdrawn'), ('withdrawn_at__isnull', False)), _connector='OR'), name='registry_circuitrevision_lifecycle_timestamps'),
        ),
        migrations.AddConstraint(
            model_name='decoderversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('published_at__isnull', True), ('state__in', ['draft', 'pending_review', 'pending_reapproval', 'changes_requested', 'rejected']), ('withdrawn_at__isnull', True)), models.Q(('published_at__isnull', False), ('state', 'published'), ('withdrawn_at__isnull', True)), models.Q(('published_at__isnull', False), ('state', 'withdrawn'), ('withdrawn_at__isnull', False)), _connector='OR'), name='registry_decoderversion_lifecycle_timestamps'),
        ),
        migrations.AddConstraint(
            model_name='machine',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('published_at__isnull', True), ('state__in', ['draft', 'pending_review', 'pending_reapproval', 'changes_requested', 'rejected']), ('withdrawn_at__isnull', True)), models.Q(('published_at__isnull', False), ('state', 'published'), ('withdrawn_at__isnull', True)), models.Q(('published_at__isnull', False), ('state', 'withdrawn'), ('withdrawn_at__isnull', False)), _connector='OR'), name='registry_machine_lifecycle_timestamps'),
        ),
        migrations.AddConstraint(
            model_name='noisemodel',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('published_at__isnull', True), ('state__in', ['draft', 'pending_review', 'pending_reapproval', 'changes_requested', 'rejected']), ('withdrawn_at__isnull', True)), models.Q(('published_at__isnull', False), ('state', 'published'), ('withdrawn_at__isnull', True)), models.Q(('published_at__isnull', False), ('state', 'withdrawn'), ('withdrawn_at__isnull', False)), _connector='OR'), name='registry_noisemodel_lifecycle_timestamps'),
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('published_at__isnull', True), ('state__in', ['draft', 'pending_review', 'pending_reapproval', 'changes_requested', 'rejected']), ('withdrawn_at__isnull', True)), models.Q(('published_at__isnull', False), ('state', 'published'), ('withdrawn_at__isnull', True)), models.Q(('published_at__isnull', False), ('state', 'withdrawn'), ('withdrawn_at__isnull', False)), _connector='OR'), name='registry_result_lifecycle_timestamps'),
        ),
    ]
