# Generated by Django 5.2.17 on 2026-09-02 09:46

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0015_record_events_and_uniform_lineage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TagAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alias', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tag_alias',
            },
        ),
        migrations.RemoveConstraint(
            model_name='recordevent',
            name='record_event_action_valid',
        ),
        migrations.AlterField(
            model_name='recordevent',
            name='action',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('edited', 'Edited'), ('resubmitted', 'Resubmitted'), ('requested_changes', 'Requested changes'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published'), ('withdrawn', 'Withdrawn'), ('restored', 'Restored'), ('revision_created', 'Revision created'), ('promoted_official', 'Promoted official'), ('deprecated', 'Deprecated'), ('merged', 'Merged'), ('added_alias', 'Added alias'), ('removed_alias', 'Removed alias'), ('admin_credit_claim_override', 'Admin credit claim override')], max_length=40),
        ),
        migrations.AlterField(
            model_name='tag',
            name='canonical_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deprecated_aliases', to='registry.tag'),
        ),
        migrations.AddConstraint(
            model_name='recordevent',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ['submitted', 'edited', 'resubmitted', 'requested_changes', 'approved', 'rejected', 'published', 'withdrawn', 'restored', 'revision_created', 'promoted_official', 'deprecated', 'merged', 'added_alias', 'removed_alias', 'admin_credit_claim_override'])), name='record_event_action_valid'),
        ),
        migrations.AddField(
            model_name='tagalias',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tag_aliases_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tagalias',
            name='removed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tag_aliases_removed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tagalias',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='registry.tag'),
        ),
        migrations.AddIndex(
            model_name='tagalias',
            index=models.Index(fields=['tag', 'is_active', 'alias'], name='idx_tag_alias_lookup'),
        ),
        migrations.AddConstraint(
            model_name='tagalias',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('alias'), condition=models.Q(('is_active', True)), name='tag_alias_active_ci_uniq'),
        ),
        migrations.AddConstraint(
            model_name='tagalias',
            constraint=models.CheckConstraint(condition=models.Q(('alias__regex', '^\\s*$'), _negated=True), name='tag_alias_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='tagalias',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_active', True), ('removed_at__isnull', True), ('removed_by__isnull', True)), models.Q(('is_active', False), ('removed_at__isnull', False), ('removed_by__isnull', False)), _connector='OR'), name='tag_alias_removal_state_valid'),
        ),
    ]
