# Generated by Django 5.2.17 on 2026-09-02 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0016_tag_aliases'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagParent',
            fields=[
                ('pk', models.CompositePrimaryKey('child_id', 'parent_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parent_memberships', to='registry.tag')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='child_memberships', to='registry.tag')),
            ],
            options={
                'db_table': 'tag_parent',
            },
        ),
        migrations.AddField(
            model_name='tag',
            name='parents',
            field=models.ManyToManyField(related_name='children', through='registry.TagParent', through_fields=('child', 'parent'), to='registry.tag'),
        ),
        migrations.AddConstraint(
            model_name='tagparent',
            constraint=models.CheckConstraint(condition=models.Q(('child', models.F('parent')), _negated=True), name='tag_parent_not_self'),
        ),
    ]
