# Generated by Django 5.2.17 on 2026-09-02 12:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0017_tag_parents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recordevent',
            name='record_event_action_valid',
        ),
        migrations.RemoveConstraint(
            model_name='tag',
            name='tag_status_valid',
        ),
        migrations.AlterField(
            model_name='recordevent',
            name='action',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('edited', 'Edited'), ('resubmitted', 'Resubmitted'), ('requested_changes', 'Requested changes'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published'), ('withdrawn', 'Withdrawn'), ('restored', 'Restored'), ('revision_created', 'Revision created'), ('promoted_official', 'Promoted official'), ('deprecated', 'Deprecated'), ('retired', 'Retired'), ('merged', 'Merged'), ('added_alias', 'Added alias'), ('removed_alias', 'Removed alias'), ('admin_credit_claim_override', 'Admin credit claim override')], max_length=40),
        ),
        migrations.AlterField(
            model_name='tag',
            name='status',
            field=models.CharField(choices=[('custom', 'Custom'), ('official', 'Official'), ('deprecated', 'Deprecated'), ('retired', 'Retired')], default='custom', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='recordevent',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ['submitted', 'edited', 'resubmitted', 'requested_changes', 'approved', 'rejected', 'published', 'withdrawn', 'restored', 'revision_created', 'promoted_official', 'deprecated', 'retired', 'merged', 'added_alias', 'removed_alias', 'admin_credit_claim_override'])), name='record_event_action_valid'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['custom', 'official', 'deprecated', 'retired'])), name='tag_status_valid'),
        ),
    ]
