# Generated by Django 5.2.17 on 2026-09-02 14:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0018_remove_recordevent_record_event_action_valid_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EczSyncRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("no_change", "No change"),
                            ("rejected", "Rejected"),
                            ("failed", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_repository", models.URLField(max_length=500)),
                (
                    "source_commit",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("workflow_run_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "workflow_run_url",
                    models.URLField(blank=True, max_length=1000, null=True),
                ),
                (
                    "archive_sha256",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "previous_source_commit",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("terms_added", models.PositiveIntegerField(default=0)),
                ("terms_retired", models.PositiveIntegerField(default=0)),
                ("names_changed", models.PositiveIntegerField(default=0)),
                ("parent_edges_added", models.PositiveIntegerField(default=0)),
                ("parent_edges_removed", models.PositiveIntegerField(default=0)),
                ("terms_restored", models.PositiveIntegerField(default=0)),
                ("diagnostics", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "ecz_sync_run",
                "indexes": [
                    models.Index(fields=["-started_at"], name="idx_ecz_sync_started"),
                    models.Index(
                        fields=["status", "-finished_at"], name="idx_ecz_sync_status"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                ["applied", "no_change", "rejected", "failed"],
                            )
                        ),
                        name="ecz_sync_run_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("source_commit__isnull", True),
                            ("source_commit__regex", "^[0-9a-f]{40}$"),
                            _connector="OR",
                        ),
                        name="ecz_sync_run_commit_sha_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("archive_sha256__isnull", True),
                            ("archive_sha256__regex", "^[0-9a-f]{64}$"),
                            _connector="OR",
                        ),
                        name="ecz_sync_run_archive_sha_valid",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EczTerm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ecz_code_id", models.CharField(max_length=200, unique=True)),
                ("raw_name", models.TextField()),
                ("display_name", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[("current", "Current"), ("retired", "Retired")],
                        default="current",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "first_seen_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="terms_first_seen",
                        to="registry.eczsyncrun",
                    ),
                ),
                (
                    "last_seen_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="terms_last_seen",
                        to="registry.eczsyncrun",
                    ),
                ),
            ],
            options={
                "db_table": "ecz_term",
            },
        ),
        migrations.CreateModel(
            name="EczParent",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "child_id",
                        "parent_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parent_memberships",
                        to="registry.eczterm",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="child_memberships",
                        to="registry.eczterm",
                    ),
                ),
            ],
            options={
                "db_table": "ecz_parent",
            },
        ),
        migrations.AddField(
            model_name="eczterm",
            name="parents",
            field=models.ManyToManyField(
                related_name="children",
                through="registry.EczParent",
                through_fields=("child", "parent"),
                to="registry.eczterm",
            ),
        ),
        migrations.CreateModel(
            name="CircuitRevisionEczTerm",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "circuit_revision_id",
                        "ecz_term_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "circuit_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ecz_term_memberships",
                        to="registry.circuitrevision",
                    ),
                ),
                (
                    "ecz_term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="circuit_memberships",
                        to="registry.eczterm",
                    ),
                ),
            ],
            options={
                "db_table": "circuit_revision_ecz_term",
            },
        ),
        migrations.AddField(
            model_name="circuitrevision",
            name="ecz_terms",
            field=models.ManyToManyField(
                related_name="circuit_revisions",
                through="registry.CircuitRevisionEczTerm",
                to="registry.eczterm",
            ),
        ),
        migrations.CreateModel(
            name="TagEczMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("revoked", "Revoked")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("mapped_at", models.DateTimeField()),
                ("mapping_note", models.TextField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revocation_note", models.TextField(blank=True, null=True)),
                (
                    "ecz_term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="native_tag_mappings",
                        to="registry.eczterm",
                    ),
                ),
                (
                    "mapped_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ecz_mappings_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ecz_mappings_revoked",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ecz_mappings",
                        to="registry.tag",
                    ),
                ),
            ],
            options={
                "db_table": "tag_ecz_mapping",
            },
        ),
        migrations.CreateModel(
            name="TagEczParent",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "tag_id",
                        "ecz_term_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ecz_term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="native_child_memberships",
                        to="registry.eczterm",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ecz_parent_memberships",
                        to="registry.tag",
                    ),
                ),
            ],
            options={
                "db_table": "tag_ecz_parent",
            },
        ),
        migrations.AddField(
            model_name="tag",
            name="ecz_parents",
            field=models.ManyToManyField(
                related_name="native_children",
                through="registry.TagEczParent",
                to="registry.eczterm",
            ),
        ),
        migrations.AddIndex(
            model_name="eczterm",
            index=models.Index(
                fields=["status", "display_name"], name="idx_ecz_term_search"
            ),
        ),
        migrations.AddConstraint(
            model_name="eczterm",
            constraint=models.CheckConstraint(
                condition=models.Q(("ecz_code_id__regex", "^[a-z0-9][a-z0-9_-]*$")),
                name="ecz_term_code_id_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="eczterm",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["current", "retired"])),
                name="ecz_term_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="eczparent",
            constraint=models.CheckConstraint(
                condition=models.Q(("child", models.F("parent")), _negated=True),
                name="ecz_parent_not_self",
            ),
        ),
        migrations.AddIndex(
            model_name="tageczmapping",
            index=models.Index(
                fields=["status", "ecz_term"], name="idx_tag_ecz_mapping_status"
            ),
        ),
        migrations.AddConstraint(
            model_name="tageczmapping",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["active", "revoked"])),
                name="tag_ecz_mapping_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="tageczmapping",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("revocation_note__isnull", True),
                        ("revoked_at__isnull", True),
                        ("revoked_by__isnull", True),
                        ("status", "active"),
                    ),
                    models.Q(
                        ("revocation_note__isnull", False),
                        ("revoked_at__isnull", False),
                        ("revoked_by__isnull", False),
                        ("status", "revoked"),
                    ),
                    _connector="OR",
                ),
                name="tag_ecz_mapping_revocation_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="tageczmapping",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("tag",),
                name="tag_one_active_ecz_mapping",
            ),
        ),
    ]
