# Generated by Django 5.2.17 on 2026-09-02 22:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0019_ecz_taxonomy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CircuitBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('validated', 'Validated'), ('committed', 'Committed'), ('failed', 'Failed')], max_length=20)),
                ('raw_manifest', models.JSONField()),
                ('normalized_manifest', models.JSONField()),
                ('validation_report', models.JSONField(default=dict)),
                ('manifest_sha256', models.CharField(max_length=64)),
                ('idempotency_key', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'circuit_batch',
            },
        ),
        migrations.CreateModel(
            name='CircuitBatchItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('client_id', models.CharField(max_length=200)),
                ('file_name', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'circuit_batch_item',
            },
        ),
        migrations.CreateModel(
            name='CircuitCollection',
            fields=[
                ('state', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('pending_reapproval', 'Pending reapproval'), ('changes_requested', 'Changes requested'), ('rejected', 'Rejected'), ('published', 'Published'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'circuit_collection',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CircuitCollectionChild',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'circuit_collection_child',
            },
        ),
        migrations.CreateModel(
            name='CircuitCollectionCodeTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'circuit_collection_code_tag',
            },
        ),
        migrations.CreateModel(
            name='CircuitCollectionEczTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'circuit_collection_ecz_term',
            },
        ),
        migrations.CreateModel(
            name='CircuitCollectionExperimentTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'circuit_collection_experiment_tag',
            },
        ),
        migrations.CreateModel(
            name='CircuitCollectionMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'circuit_collection_member',
            },
        ),
        migrations.RemoveConstraint(
            model_name='recordevent',
            name='record_event_one_subject',
        ),
        migrations.RemoveConstraint(
            model_name='recordevent',
            name='record_event_action_valid',
        ),
        migrations.RemoveConstraint(
            model_name='recordhistory',
            name='record_history_kind_valid',
        ),
        migrations.AddField(
            model_name='benchmarkattempt',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
        migrations.AddField(
            model_name='benchmarkrevision',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
        migrations.AddField(
            model_name='circuitrevision',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
        migrations.AddField(
            model_name='decoderversion',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
        migrations.AddField(
            model_name='evaluatorrelease',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
        migrations.AddField(
            model_name='machine',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
        migrations.AddField(
            model_name='noisemodel',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
        migrations.AddField(
            model_name='result',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
        migrations.AddField(
            model_name='tag',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
        migrations.AlterField(
            model_name='recordevent',
            name='action',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('edited', 'Edited'), ('resubmitted', 'Resubmitted'), ('requested_changes', 'Requested changes'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published'), ('withdrawn', 'Withdrawn'), ('restored', 'Restored'), ('revision_created', 'Revision created'), ('promoted_official', 'Promoted official'), ('deprecated', 'Deprecated'), ('retired', 'Retired'), ('merged', 'Merged'), ('added_alias', 'Added alias'), ('removed_alias', 'Removed alias'), ('admin_credit_claim_override', 'Admin credit claim override'), ('made_public', 'Made public'), ('made_private', 'Made private'), ('member_added', 'Circuit added'), ('member_removed', 'Circuit removed'), ('child_added', 'Subcollection added'), ('child_removed', 'Subcollection removed')], max_length=40),
        ),
        migrations.AlterField(
            model_name='recordhistory',
            name='record_kind',
            field=models.CharField(choices=[('decoder', 'Decoder version'), ('noise_model', 'Noise model'), ('circuit', 'Circuit revision'), ('machine', 'Machine'), ('result', 'Result'), ('tag', 'Tag'), ('benchmark', 'Benchmark revision'), ('benchmark_attempt', 'Benchmark attempt'), ('evaluator', 'Evaluator release'), ('collection', 'Circuit collection')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='benchmarkattempt',
            constraint=models.CheckConstraint(condition=models.Q(('visibility__in', ['public', 'private'])), name='registry_benchmarkattempt_visibility_valid'),
        ),
        migrations.AddConstraint(
            model_name='benchmarkrevision',
            constraint=models.CheckConstraint(condition=models.Q(('visibility__in', ['public', 'private'])), name='registry_benchmarkrevision_visibility_valid'),
        ),
        migrations.AddConstraint(
            model_name='circuitrevision',
            constraint=models.CheckConstraint(condition=models.Q(('visibility__in', ['public', 'private'])), name='registry_circuitrevision_visibility_valid'),
        ),
        migrations.AddConstraint(
            model_name='decoderversion',
            constraint=models.CheckConstraint(condition=models.Q(('visibility__in', ['public', 'private'])), name='registry_decoderversion_visibility_valid'),
        ),
        migrations.AddConstraint(
            model_name='evaluatorrelease',
            constraint=models.CheckConstraint(condition=models.Q(('visibility__in', ['public', 'private'])), name='evaluator_release_visibility_valid'),
        ),
        migrations.AddConstraint(
            model_name='machine',
            constraint=models.CheckConstraint(condition=models.Q(('visibility__in', ['public', 'private'])), name='registry_machine_visibility_valid'),
        ),
        migrations.AddConstraint(
            model_name='noisemodel',
            constraint=models.CheckConstraint(condition=models.Q(('visibility__in', ['public', 'private'])), name='registry_noisemodel_visibility_valid'),
        ),
        migrations.AddConstraint(
            model_name='recordhistory',
            constraint=models.CheckConstraint(condition=models.Q(('record_kind__in', ['decoder', 'noise_model', 'circuit', 'machine', 'result', 'tag', 'benchmark', 'benchmark_attempt', 'evaluator', 'collection'])), name='record_history_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.CheckConstraint(condition=models.Q(('visibility__in', ['public', 'private'])), name='registry_result_visibility_valid'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.CheckConstraint(condition=models.Q(('visibility__in', ['public', 'private'])), name='tag_visibility_valid'),
        ),
        migrations.AddField(
            model_name='circuitbatch',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='circuit_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='circuitbatchitem',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='registry.circuitbatch'),
        ),
        migrations.AddField(
            model_name='circuitbatchitem',
            name='circuit_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batch_items', to='registry.circuitrevision'),
        ),
        migrations.AddField(
            model_name='circuitbatchitem',
            name='sampling_artifact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='circuit_batch_items', to='registry.artifact'),
        ),
        migrations.AddField(
            model_name='circuitcollection',
            name='history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='circuit_collections', to='registry.recordhistory'),
        ),
        migrations.AddField(
            model_name='circuitcollection',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='circuit_collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recordevent',
            name='circuit_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='record_events', to='registry.circuitcollection'),
        ),
        migrations.AddConstraint(
            model_name='recordevent',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ['submitted', 'edited', 'resubmitted', 'requested_changes', 'approved', 'rejected', 'published', 'withdrawn', 'restored', 'revision_created', 'promoted_official', 'deprecated', 'retired', 'merged', 'added_alias', 'removed_alias', 'admin_credit_claim_override', 'made_public', 'made_private', 'member_added', 'member_removed', 'child_added', 'child_removed'])), name='record_event_action_valid'),
        ),
        migrations.AddConstraint(
            model_name='recordevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('pk__isnull', True), models.Q(('pk__isnull', True), _negated=True)), models.Q(('decoder_version__isnull', False), ('noise_model__isnull', True), ('circuit_revision__isnull', True), ('machine__isnull', True), ('result__isnull', True), ('tag__isnull', True), ('benchmark_revision__isnull', True), ('benchmark_attempt__isnull', True), ('evaluator_release__isnull', True), ('circuit_collection__isnull', True)), models.Q(('noise_model__isnull', False), ('decoder_version__isnull', True), ('circuit_revision__isnull', True), ('machine__isnull', True), ('result__isnull', True), ('tag__isnull', True), ('benchmark_revision__isnull', True), ('benchmark_attempt__isnull', True), ('evaluator_release__isnull', True), ('circuit_collection__isnull', True)), models.Q(('circuit_revision__isnull', False), ('decoder_version__isnull', True), ('noise_model__isnull', True), ('machine__isnull', True), ('result__isnull', True), ('tag__isnull', True), ('benchmark_revision__isnull', True), ('benchmark_attempt__isnull', True), ('evaluator_release__isnull', True), ('circuit_collection__isnull', True)), models.Q(('machine__isnull', False), ('decoder_version__isnull', True), ('noise_model__isnull', True), ('circuit_revision__isnull', True), ('result__isnull', True), ('tag__isnull', True), ('benchmark_revision__isnull', True), ('benchmark_attempt__isnull', True), ('evaluator_release__isnull', True), ('circuit_collection__isnull', True)), models.Q(('result__isnull', False), ('decoder_version__isnull', True), ('noise_model__isnull', True), ('circuit_revision__isnull', True), ('machine__isnull', True), ('tag__isnull', True), ('benchmark_revision__isnull', True), ('benchmark_attempt__isnull', True), ('evaluator_release__isnull', True), ('circuit_collection__isnull', True)), models.Q(('tag__isnull', False), ('decoder_version__isnull', True), ('noise_model__isnull', True), ('circuit_revision__isnull', True), ('machine__isnull', True), ('result__isnull', True), ('benchmark_revision__isnull', True), ('benchmark_attempt__isnull', True), ('evaluator_release__isnull', True), ('circuit_collection__isnull', True)), models.Q(('benchmark_revision__isnull', False), ('decoder_version__isnull', True), ('noise_model__isnull', True), ('circuit_revision__isnull', True), ('machine__isnull', True), ('result__isnull', True), ('tag__isnull', True), ('benchmark_attempt__isnull', True), ('evaluator_release__isnull', True), ('circuit_collection__isnull', True)), models.Q(('benchmark_attempt__isnull', False), ('decoder_version__isnull', True), ('noise_model__isnull', True), ('circuit_revision__isnull', True), ('machine__isnull', True), ('result__isnull', True), ('tag__isnull', True), ('benchmark_revision__isnull', True), ('evaluator_release__isnull', True), ('circuit_collection__isnull', True)), models.Q(('evaluator_release__isnull', False), ('decoder_version__isnull', True), ('noise_model__isnull', True), ('circuit_revision__isnull', True), ('machine__isnull', True), ('result__isnull', True), ('tag__isnull', True), ('benchmark_revision__isnull', True), ('benchmark_attempt__isnull', True), ('circuit_collection__isnull', True)), models.Q(('circuit_collection__isnull', False), ('decoder_version__isnull', True), ('noise_model__isnull', True), ('circuit_revision__isnull', True), ('machine__isnull', True), ('result__isnull', True), ('tag__isnull', True), ('benchmark_revision__isnull', True), ('benchmark_attempt__isnull', True), ('evaluator_release__isnull', True)), _connector='OR'), name='record_event_one_subject'),
        ),
        migrations.AddField(
            model_name='circuitcollectionchild',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_children_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='circuitcollectionchild',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parent_memberships', to='registry.circuitcollection'),
        ),
        migrations.AddField(
            model_name='circuitcollectionchild',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='child_memberships', to='registry.circuitcollection'),
        ),
        migrations.AddField(
            model_name='circuitcollectionchild',
            name='removed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collection_children_removed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='circuitcollectioncodetag',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='code_tag_memberships', to='registry.circuitcollection'),
        ),
        migrations.AddField(
            model_name='circuitcollectioncodetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_code_memberships', to='registry.tag'),
        ),
        migrations.AddField(
            model_name='circuitcollection',
            name='code_tags',
            field=models.ManyToManyField(related_name='code_circuit_collections', through='registry.CircuitCollectionCodeTag', to='registry.tag'),
        ),
        migrations.AddField(
            model_name='circuitcollectioneczterm',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ecz_term_memberships', to='registry.circuitcollection'),
        ),
        migrations.AddField(
            model_name='circuitcollectioneczterm',
            name='ecz_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_memberships', to='registry.eczterm'),
        ),
        migrations.AddField(
            model_name='circuitcollection',
            name='ecz_terms',
            field=models.ManyToManyField(related_name='circuit_collections', through='registry.CircuitCollectionEczTerm', to='registry.eczterm'),
        ),
        migrations.AddField(
            model_name='circuitcollectionexperimenttag',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experiment_tag_memberships', to='registry.circuitcollection'),
        ),
        migrations.AddField(
            model_name='circuitcollectionexperimenttag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_experiment_memberships', to='registry.tag'),
        ),
        migrations.AddField(
            model_name='circuitcollection',
            name='experiment_tags',
            field=models.ManyToManyField(related_name='experiment_circuit_collections', through='registry.CircuitCollectionExperimentTag', to='registry.tag'),
        ),
        migrations.AddField(
            model_name='circuitcollectionmember',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_circuits_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='circuitcollectionmember',
            name='circuit_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_memberships', to='registry.circuitrevision'),
        ),
        migrations.AddField(
            model_name='circuitcollectionmember',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='circuit_memberships', to='registry.circuitcollection'),
        ),
        migrations.AddField(
            model_name='circuitcollectionmember',
            name='removed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collection_circuits_removed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='circuitbatch',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['validated', 'committed', 'failed'])), name='circuit_batch_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='circuitbatch',
            constraint=models.CheckConstraint(condition=models.Q(('manifest_sha256__regex', '^[0-9a-f]{64}$')), name='circuit_batch_digest_valid'),
        ),
        migrations.AddConstraint(
            model_name='circuitbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('submitted_by', 'idempotency_key'), name='circuit_batch_idempotency_uniq'),
        ),
        migrations.AddConstraint(
            model_name='circuitbatchitem',
            constraint=models.UniqueConstraint(fields=('batch', 'position'), name='circuit_batch_item_position_uniq'),
        ),
        migrations.AddConstraint(
            model_name='circuitbatchitem',
            constraint=models.UniqueConstraint(fields=('batch', 'client_id'), name='circuit_batch_item_client_uniq'),
        ),
        migrations.AddConstraint(
            model_name='circuitbatchitem',
            constraint=models.UniqueConstraint(fields=('batch', 'file_name'), name='circuit_batch_item_file_uniq'),
        ),
        migrations.AddConstraint(
            model_name='circuitbatchitem',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1)), name='circuit_batch_item_position_positive'),
        ),
        migrations.AddConstraint(
            model_name='circuitcollectionchild',
            constraint=models.UniqueConstraint(fields=('collection', 'child'), name='collection_child_once'),
        ),
        migrations.AddConstraint(
            model_name='circuitcollectionchild',
            constraint=models.UniqueConstraint(condition=models.Q(('removed_at__isnull', True)), fields=('collection', 'position'), name='collection_active_child_position_uniq'),
        ),
        migrations.AddConstraint(
            model_name='circuitcollectionchild',
            constraint=models.CheckConstraint(condition=models.Q(('collection', models.F('child')), _negated=True), name='collection_child_not_self'),
        ),
        migrations.AddConstraint(
            model_name='circuitcollectionchild',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1)), name='collection_child_position_positive'),
        ),
        migrations.AddConstraint(
            model_name='circuitcollectionchild',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('removed_at__isnull', True), ('removed_by__isnull', True)), models.Q(('removed_at__isnull', False), ('removed_by__isnull', False)), _connector='OR'), name='collection_child_removal_valid'),
        ),
        migrations.AddConstraint(
            model_name='circuitcollectioncodetag',
            constraint=models.UniqueConstraint(fields=('collection', 'tag'), name='collection_code_tag_uniq'),
        ),
        migrations.AddConstraint(
            model_name='circuitcollectioneczterm',
            constraint=models.UniqueConstraint(fields=('collection', 'ecz_term'), name='collection_ecz_term_uniq'),
        ),
        migrations.AddConstraint(
            model_name='circuitcollectionexperimenttag',
            constraint=models.UniqueConstraint(fields=('collection', 'tag'), name='collection_experiment_tag_uniq'),
        ),
        migrations.AddIndex(
            model_name='circuitcollection',
            index=models.Index(fields=['visibility', 'state', 'name'], name='idx_collection_public_name'),
        ),
        migrations.AddIndex(
            model_name='circuitcollection',
            index=models.Index(fields=['submitted_by', '-created_at'], name='idx_collection_owner_created'),
        ),
        migrations.AddConstraint(
            model_name='circuitcollection',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('published_at__isnull', True), ('state__in', ['draft', 'pending_review', 'pending_reapproval', 'changes_requested', 'rejected']), ('withdrawn_at__isnull', True)), models.Q(('published_at__isnull', False), ('state', 'published'), ('withdrawn_at__isnull', True)), models.Q(('published_at__isnull', False), ('state', 'withdrawn'), ('withdrawn_at__isnull', False)), _connector='OR'), name='registry_circuitcollection_lifecycle_timestamps'),
        ),
        migrations.AddConstraint(
            model_name='circuitcollection',
            constraint=models.CheckConstraint(condition=models.Q(('visibility__in', ['public', 'private'])), name='registry_circuitcollection_visibility_valid'),
        ),
        migrations.AddConstraint(
            model_name='circuitcollectionmember',
            constraint=models.UniqueConstraint(fields=('collection', 'circuit_revision'), name='collection_circuit_once'),
        ),
        migrations.AddConstraint(
            model_name='circuitcollectionmember',
            constraint=models.UniqueConstraint(condition=models.Q(('removed_at__isnull', True)), fields=('collection', 'position'), name='collection_active_circuit_position_uniq'),
        ),
        migrations.AddConstraint(
            model_name='circuitcollectionmember',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1)), name='collection_circuit_position_positive'),
        ),
        migrations.AddConstraint(
            model_name='circuitcollectionmember',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('removed_at__isnull', True), ('removed_by__isnull', True)), models.Q(('removed_at__isnull', False), ('removed_by__isnull', False)), _connector='OR'), name='collection_circuit_removal_valid'),
        ),
    ]
