# Generated by Django 5.2.17 on 2026-09-16 11:07

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0020_circuitbatch_circuitbatchitem_circuitcollection_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="circuitrevision",
            name="noise_parameter",
            field=models.FloatField(
                blank=True,
                help_text=(
                    "Optional physical noise parameter; its meaning is defined "
                    "by the noise model."
                ),
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1.7976931348623157e308),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="circuitrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("noise_parameter__isnull", True),
                    models.Q(
                        ("noise_parameter__gte", 0),
                        ("noise_parameter__lte", 1.7976931348623157e308),
                    ),
                    _connector="OR",
                ),
                name="circuit_noise_parameter_finite_nonnegative",
            ),
        ),
    ]
