# Generated by Django 5.2.17 on 2026-09-16 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0022_backfill_demo_noise_parameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircuitSlugAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slug_aliases', to='registry.circuitrevision')),
            ],
        ),
    ]
