# Generated by Django 5.2.17 on 2026-09-01 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_daily_quote_schedule(apps, schema_editor):
    schedule = apps.get_model("pages", "DailyQuoteSchedule")
    schedule.objects.get_or_create(id=1, defaults={"day_offset": 0})


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyQuoteSchedule",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("day_offset", models.BigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="daily_quote_schedule_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "daily_quote_schedule",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)),
                        name="daily_quote_schedule_singleton",
                    )
                ],
            },
        ),
        migrations.RunPython(seed_daily_quote_schedule, migrations.RunPython.noop),
    ]
