# Generated by Django 5.2.17 on 2026-08-30 14:50

import accounts.managers
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'account',
                'constraints': [models.CheckConstraint(condition=models.Q(('display_name__regex', '^\\s*$'), _negated=True), name='account_display_name_nonblank'), models.CheckConstraint(condition=models.Q(('password__startswith', '!')), name='account_password_unusable')],
            },
            managers=[
                ('objects', accounts.managers.AccountManager()),
            ],
        ),
        migrations.CreateModel(
            name='ExternalIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('orcid', 'ORCID')], max_length=10)),
                ('provider_subject', models.TextField()),
                ('public_identifier', models.TextField()),
                ('profile_url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_authenticated_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'external_identity',
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_subject'), name='external_identity_provider_subject_uniq'), models.UniqueConstraint(fields=('account', 'provider'), name='external_identity_account_provider_uniq')],
            },
        ),
    ]
