# Generated by Django 5.2.17 on 2026-08-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='externalidentity',
            constraint=models.CheckConstraint(condition=models.Q(('provider__in', ['github', 'orcid'])), name='external_identity_provider_valid'),
        ),
    ]
