# Generated by Django 5.2.17 on 2026-09-02 22:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_externalidentity_external_identity_provider_valid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalApiToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(max_length=24, unique=True)),
                ('secret_digest', models.CharField(max_length=64)),
                ('display_prefix', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('scopes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'personal_api_token',
                'indexes': [models.Index(fields=['account', '-created_at'], name='idx_api_token_account_created')],
                'constraints': [models.CheckConstraint(condition=models.Q(('secret_digest__regex', '^[0-9a-f]{64}$')), name='personal_api_token_digest_valid'), models.CheckConstraint(condition=models.Q(('name__regex', '^\\s*$'), _negated=True), name='personal_api_token_name_nonblank')],
            },
        ),
    ]
